import {
  ConnectedAccount,
  PortfolioHolding,
  Transaction,
  WalletAssetBalance,
} from "@/types";

export const PORTFOLIO_HOLDINGS: PortfolioHolding[] = [
  {
    symbol: "BTC",
    assetClass: "crypto",
    amount: 0.842,
    avgEntry: 64200,
    currentPrice: 71284.5,
    valueUsd: 60001.55,
    pnlUsd: 5965.16,
    pnlPercent: 11.04,
    locked: false,
  },
  {
    symbol: "ETH",
    assetClass: "crypto",
    amount: 6.4,
    avgEntry: 3520,
    currentPrice: 3845.22,
    valueUsd: 24609.41,
    pnlUsd: 2081.41,
    pnlPercent: 9.24,
    locked: false,
  },
  {
    symbol: "SOL",
    assetClass: "crypto",
    amount: 48.2,
    avgEntry: 195.4,
    currentPrice: 178.93,
    valueUsd: 8624.39,
    pnlUsd: -793.85,
    pnlPercent: -8.43,
    locked: true,
  },
  {
    symbol: "EUR/USD",
    assetClass: "forex",
    amount: 25000,
    avgEntry: 1.079,
    currentPrice: 1.0842,
    valueUsd: 27105,
    pnlUsd: 130,
    pnlPercent: 0.48,
    locked: true,
  },
  {
    symbol: "XAU/USD",
    assetClass: "forex",
    amount: 12,
    avgEntry: 2298.5,
    currentPrice: 2342.8,
    valueUsd: 28113.6,
    pnlUsd: 531.6,
    pnlPercent: 1.93,
    locked: false,
  },
];

export const CONNECTED_ACCOUNTS: ConnectedAccount[] = [
  {
    id: "acc-binance",
    provider: "Binance",
    type: "exchange",
    status: "connected",
    permission: "trade",
    lastSync: new Date(Date.now() - 2 * 60000).toISOString(),
    logoColor: "#F0B90B",
  },
  {
    id: "acc-bybit",
    provider: "Bybit",
    type: "exchange",
    status: "connected",
    permission: "read-only",
    lastSync: new Date(Date.now() - 9 * 60000).toISOString(),
    logoColor: "#F7A600",
  },
  {
    id: "acc-okx",
    provider: "OKX",
    type: "exchange",
    status: "disconnected",
    permission: "read-only",
    lastSync: new Date(Date.now() - 86400000).toISOString(),
    logoColor: "#FFFFFF",
  },
  {
    id: "acc-kraken",
    provider: "Kraken",
    type: "exchange",
    status: "error",
    permission: "read-only",
    lastSync: new Date(Date.now() - 3 * 3600000).toISOString(),
    logoColor: "#5741D9",
  },
  {
    id: "acc-oanda",
    provider: "OANDA",
    type: "broker",
    status: "connected",
    permission: "trade",
    lastSync: new Date(Date.now() - 4 * 60000).toISOString(),
    logoColor: "#5B5FEF",
  },
  {
    id: "acc-ibkr",
    provider: "Interactive Brokers",
    type: "broker",
    status: "disconnected",
    permission: "read-only",
    lastSync: new Date(Date.now() - 7 * 86400000).toISOString(),
    logoColor: "#8B5CF6",
  },
];

export const WALLET_BALANCES: WalletAssetBalance[] = [
  { symbol: "BTC", assetClass: "crypto", available: 0.742, locked: 0.1, usdValue: 60001.55 },
  { symbol: "ETH", assetClass: "crypto", available: 6.4, locked: 0, usdValue: 24609.41 },
  { symbol: "USDT", assetClass: "crypto", available: 12500, locked: 0, usdValue: 12500 },
  { symbol: "USD", assetClass: "fiat", available: 18420.32, locked: 27105, usdValue: 45525.32 },
  { symbol: "EUR", assetClass: "fiat", available: 4210.0, locked: 0, usdValue: 4548.2 },
  { symbol: "NGN", assetClass: "fiat", available: 2_150_000, locked: 0, usdValue: 1340.6 },
];

export const TRANSACTIONS: Transaction[] = [
  {
    id: "tx-1001",
    type: "deposit",
    asset: "BTC",
    amount: 0.25,
    usdValue: 17821.13,
    method: "Crypto transfer",
    status: "completed",
    date: new Date(Date.now() - 2 * 86400000).toISOString(),
    fee: 0,
  },
  {
    id: "tx-1002",
    type: "withdrawal",
    asset: "USD",
    amount: 5000,
    usdValue: 5000,
    method: "Bank transfer",
    status: "completed",
    date: new Date(Date.now() - 5 * 86400000).toISOString(),
    fee: 15,
    destination: "Bank •••• 4421",
  },
  {
    id: "tx-1003",
    type: "deposit",
    asset: "USDT",
    amount: 8000,
    usdValue: 8000,
    method: "Crypto transfer",
    status: "completed",
    date: new Date(Date.now() - 6 * 86400000).toISOString(),
    fee: 0,
  },
  {
    id: "tx-1004",
    type: "withdrawal",
    asset: "ETH",
    amount: 1.2,
    usdValue: 4614.26,
    method: "Crypto transfer",
    status: "pending",
    date: new Date(Date.now() - 40 * 60000).toISOString(),
    fee: 0.002,
    destination: "0x9F3a...e21C",
  },
  {
    id: "tx-1005",
    type: "deposit",
    asset: "USD",
    amount: 12000,
    usdValue: 12000,
    method: "Debit/Credit card",
    status: "completed",
    date: new Date(Date.now() - 9 * 86400000).toISOString(),
    fee: 36,
  },
  {
    id: "tx-1006",
    type: "withdrawal",
    asset: "USDT",
    amount: 3000,
    usdValue: 3000,
    method: "Crypto transfer",
    status: "failed",
    date: new Date(Date.now() - 11 * 86400000).toISOString(),
    fee: 1,
    destination: "TQn9Y2...4ZbX",
  },
  {
    id: "tx-1007",
    type: "deposit",
    asset: "EUR",
    amount: 3500,
    usdValue: 3783.5,
    method: "Bank transfer",
    status: "completed",
    date: new Date(Date.now() - 14 * 86400000).toISOString(),
    fee: 0,
  },
];

export const DAILY_LOSS_LIMIT_USD = 2500;
export const DAILY_LOSS_USED_USD = 640;
export const MAX_DRAWDOWN_LIMIT_PCT = 15;
export const CURRENT_DRAWDOWN_PCT = 4.8;
